# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.87.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

  end

  lane :setup_library do
    carthage(command: "bootstrap", platform: "iOS", use_binaries:false)
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: 'CaptureUploaderSW')
  end

  desc "Runs UI tests"
  lane :screenshot do
    snapshot(scheme: 'CaptureUploaderSW')
  end
  
  desc "Submit a new Beta Build to DeployGate"
  lane :dg do |options|
    gym(scheme: 'CaptureUploaderSW_Staging', export_method: 'development', clean: true)
    deploygate(
        api_token: ENV['DEPLOYGATE_API_KEY'],
        user: ENV['DEPLOYGATE_USER'],
        message: "Message:" + options[:message],
    )
  end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(message: "スナップショットの取得が完了しました") if lane == :screenshot

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    slack(message: exception.message, success: false) if lane == :screenshot

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
